baseURL = "https://evkx.net/"
languageCode = "en"
defaultContentLanguage = "en"

contentDir = "content"
staticDir = "static"
publishDir = "public"

title = "Electric Vehicle Knowledge eXchange"
theme = "hugo-theme-evkx2"
metadataFormat = "yaml"
pluralizeListTitles = false
preservetaxonomynames = true
enableEmoji = true
enableGitInfo = false
disableKinds = ["RSS"] # page home section taxonomy taxonomyTerm RSS sitemap robotsTXT 404

[languages]
  [languages.en]
    title = "evkx.net"
    languageName = "English"
    weight = 1
  [languages.nb]
    title = "evkx.net"
    languageName = "Norsk"
    weight = 2
  [languages.sv]
    title = "evkx.net"
    languageName = "Svensk"
    weight = 3


[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "dracula"

[markup.tableOfContents]
startLevel = 2
endLevel = 2
ordered = false

[blackfriday]
fractions = false # disable automatic fraction rendering

[params]
editURL = "https://github.com/evkx/evkx.github.io/blob/master/content/"
noHomeIcon = true # default is false
noSearch = true # default is false
showVisitedLinks = false # default is false


[outputs]
home = ["HTML", "JSON"] # JSON generates index.json file used by search
